name: CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FUNCTION_NAME: Palma_Voluum

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions          
        run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --entry-point=main
          --region=us-central1
          --timeout=530
          --project=${{ secrets.PROJECT_ID }}
          --memory=4096MB
          --runtime=python39
          --trigger-http
          --service-account=${{ secrets.GCP_SA }}
          --set-env-vars=EMAIL=${{ secrets.EMAIL }},VPWD=${{ secrets.VPWD }},PROJECT_ID=${{ secrets.PROJECT_ID }}
